### ISSUE TITLE
Prevent project generation if inputs not valid

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/gwt-boot-starter-nalu#23]
If you input invalid settings for group id or artefact id the project generator doesn't prevent the project generation. The validator checks and marks empty fields for example but doesn't disable the generator button.
The validator also doesn't check for invalid inputs like "." or "+++" or "***". If you try to generate the project with this inputs the request ends with a HTTP 503.

**Comment by FrankHossfeld** [comment]
Good point!

**Comment by FrankHossfeld** [comment]
Fixed

**Comment by TDesjardins** [comment]
Thanks!

**Comment by TDesjardins** [comment]
Looks good!
