### ISSUE TITLE
Many issues on IE 11

### ISSUE THREAD

**Issue by eguardiola** [NaluKit/gwt-boot-starter-nalu#4]
![2018-10-05 09_30_23-nalu initializer - internet explorer](https://user-images.githubusercontent.com/13049689/46521969-8efbc080-c881-11e8-9827-2d4afd4c4cb0.png)

Recently domino fixed many issues on IE 11, may be helps...

**Comment by vegegoku** [comment]
i will start working on them

**Comment by vegegoku** [comment]
all issues have been fixed
the IE 11, is stupid enough that it does not know how to apply 2 styles to the element in one call.

I still need just little time till i can push a new version.
@eguardiola thank you for reporting

**Comment by eguardiola** [comment]
Thanks! And yes, we are suffeering the pain of IE 11 a lot xDD
